### ISSUE TITLE
Ajouter des liens pour expliquer les notions

### ISSUE THREAD

**Issue by Vayel** [entwanne/sortie-de-python-3-6#2]
Les notions d'unpacking, de descripteur, etc. sont abordées dans des tutos sur ZdS. Il me semble intéressant d'y faire référence.

**Comment by entwanne** [comment]
Ça ne me semble pas nécessaire, mais pourquoi pas.

**Comment by entwanne** [comment]
Fait. (32a6b7a147a96b26815bfc2b34ccf081e1bc6435)
